### PR TITLE
update bananapim5 acs.bin for new ddr

### PR DESCRIPTION
**Pull request by Dangku**

### CODE REVIEW

**Comment by chewitt** [comment]
@Dangku to confirm, this supports existing and new boards?

**Comment by Dangku** [comment]
The latest batch hardware replaced a new dram IC, acs.bin must be changed.

**Comment by chewitt** [comment]
Does the new acs.bin support the older (original) boards AND new boards with updated RAM, or only the new boards?

**Comment by Dangku** [comment]
both support the older boards and new boards

**Pull request merged**
