### PR TITLE
include path to LD_LIBRARY when using qemu

### PR DESCRIPTION
**Pull request by heitbaum**
Ref:
- https://github.com/LibreELEC/LibreELEC.tv/pull/9084
- https://github.com/LibreELEC/LibreELEC.tv/issues/9056

### CODE REVIEW

**Comment by heitbaum** [comment]
Tested and working along with https://github.com/LibreELEC/LibreELEC.tv/pull/9084

Ref:
- https://github.com/heitbaum/actions/actions/runs/9909519095/job/27377762825

Both x86_64 binaries (static and shared) now work.

IMG_0384

**Comment by chewitt** [comment]
Is it possible for LD_LIBRARY path to be different on other platforms?, i.e. should we make this something with a default value for LE use, but allow it to be overridden with a variable?

**Comment by heitbaum** [comment]
> Is it possible for LD_LIBRARY path to be different on other platforms?, i.e. should we make this something with a default value for LE use, but allow it to be overridden with a variable?

Is this what you were thinking.

**Review by chewitt — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
