### PR TITLE
add fip for Radxa Zero 2

### PR DESCRIPTION
**Pull request by RadxaYuntian**
Signed-off-by: Yuntian Zhang <yt@radxa.com>

### CODE REVIEW

**Comment by RadxaYuntian** [comment]
Thought FIP was broken when I could not boot `u-boot.bin.sd.bin` from microSD. Turned out I need to flash `u-boot.bin` and all is good.

**Comment by chewitt** [comment]
@RadxaYuntian I see this failure when trying to boot the Zero2 board https://pastebin.com/raw/mXQEJN9f .. note that LE will have picked u-boot.bin.sd.bin to create the .img file for writing to SD card. I've seen the comment about using u-boot.bin but this makes no sense to me; we are building u-boot from sources https://github.com/chewitt/u-boot/commits/amlogic-2022.01 (that work on a range of other G12B boards) and we are using the standard signing recipe (used on a range of other G12B boards). Are there newer versions of the FIPs available?

**Comment by RadxaYuntian** [comment]
I have confirmed the issue with your branch. I also double checked with our branch and the generated u-boot.bin worked fine. I'll see what's the difference between our branches.

**Comment by RadxaYuntian** [comment]
Seems we reached U-Boot. The error message is printed by [this line](https://github.com/chewitt/u-boot/blob/6528cb137136302d338bd33ddeb2079987d9f3af/drivers/serial/serial-uclass.c#L154). Gonna check why it cannot load meson UART driver.

**Comment by RadxaYuntian** [comment]
OK so I traced the issue to [this line](https://github.com/chewitt/u-boot/blob/6528cb137136302d338bd33ddeb2079987d9f3af/drivers/serial/serial-uclass.c#L44) then I realized the cleaned up DTB you sent before was indeed missing alias for `serial0`. I [corrected it](https://github.com/radxa/kernel/pull/10#issuecomment-1014126292) myself, but was not aware how this was used back then :facepalm: Adding `serial0 = &uart_AO;` to meson-g12b-radxa-zero2.dts `aliases` section fixed this issue. I was able to usb boot with `u-boot.bin` and follow [your instruction](https://github.com/chewitt/u-boot/blob/amlogic-2022.01/doc/board/amlogic/radxa-zero2.rst#image-creation) to boot from eMMC.

**Comment by chewitt** [comment]
Indeed that was missing from kernel (and thus u-boot) sources. With that added I've been able to boot the Zero2 board from SD card and eMMC using u-boot.bin.sd.bin (as normal). I can see some minors that still need to be fixed in the dts but it's clear the FIPs are good so happy to merge these now. Thanks!

**Pull request merged**
